using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.MainMenu.UI;

[GenerateTypedNameReferences]
public sealed partial class MainMenuScreen : Control
{
    public MainMenuScreen()
    {
        RobustXamlLoader.Load(this);
        
        LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);
        LayoutContainer.SetAnchorPreset(VBox, LayoutContainer.LayoutPreset.Center);
        LayoutContainer.SetMarginRight(VBox, -25);
        LayoutContainer.SetMarginTop(VBox, 30);
        LayoutContainer.SetGrowHorizontal(VBox, LayoutContainer.GrowDirection.Begin);
    }
}